### ISSUE TITLE
Model manipulation/fitting

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#13]
Generated from trello features:
- [fit gaussians](https://trello.com/c/5JgCFc8M)
- [fit continuum](https://trello.com/c/vhjqOWZx)

**Comment by ibusko** [comment]
I similar feature as described in #1 (spectrum arithmetic) should be available in the compound model manager widget. The current version implements a simple sum of all the components in the "active" list, but astropy can easily accommodate more complex compositions.

In order to enable that, we need first to come up with a way of naming each component in the active list. Thus each name can be used as a "variable" in the math expression.

A question: should a compound model thus defined be also named and be available for subsequent expressions? This capability, already existing in astropy, leads to interesting consequences regarding GUI design.

Btw, I suggest that we change the name of the classes such as SpectralModelManager, to make explicit that their goal is to handle a composite model. E.g. SpectralModelManager would become  CompoundSpectralModelManager, or CompoundModelManager.

**Comment by ibusko** [comment]
As for naming components in the active list, the Iris VO SED tool had exactly the same problem. The adopted solution uses a simple pattern like "c1", "c2", "c3", for naming each component. As components are deleted and added to the list, the name just keeps advancing in the pattern.

There is no ability to let users define names. That seemed simple and user-friendly enough, and very straightforward to implement.

**Comment by ibusko** [comment]
This comment relates specifically to the continuum fitting requirement (https://trello.com/c/vhjqOWZx)

A non-trivial task regards the use of Polynomial subclasses. The reason is that we must provide, in the GUI, a way for the user to change the Polynomial degree. It turns out that astropy Polynomial instances cannot change their degree. Once created, the only way to change the degree is to replace the instance by a new one. This is understandable from the software architecture standpoint, because the degree governs much of the internal structure of the object. 

Current version of the model manager (as of 2-27-2015) supports polynomials mixed with other functional forms, but doesn't allow the degree to change. The degree is defined when instantiating the polynomial, to a fixed value of 2. This is appropriate for basic testing, but clearly undesirable in the production version.

**Comment by ibusko** [comment]
When adding astropy components to the active model, the setArrays(x,y) method should be called so the added components will have their parameters roughly adjusted to the data values. Otherwise, the non-linear fit may end up in secondary minima.

**Comment by SaOgaz** [comment]
Closing, repository being archived.
