### ISSUE TITLE
Controller design

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#17]
We have the Models. We have the Views. Now we need the Controller.

Thoughts?

**Comment by stscieisenhamer** [comment]
In other prototypes, the approach being taken was a hub/messaging system, much like glue/hub.
The particular was more along the Qt signal/slot paradigm.

Initial question: Messaging system or something else?

The other prototypes were going with the messaging only because it makes it really easy to prototype.

**Comment by ibusko** [comment]
We briefly started talking yesterday about what signals exactly we want. Maybe we should come up today with that list.

On Feb 20, 2015, at 10:26 AM, Jonathan Eisenhamer <notifications@github.com<mailto:notifications@github.com>> wrote:

In other prototypes, the approach being taken was a hub/messaging system, much like glue/hub.
The particular was more along the Qt signal/slot paradigm.

Initial question: Messaging system or something else?

**Comment by stscieisenhamer** [comment]
If signalling is the approach, lets start the list here, modified originally from [specview_signals](https://github.com/spacetelescope/specview/blob/master/proto/specview_signals.py) This is a checklist where check indicates accepted.
- [ ] DataRefresh: Re-read all data (including astropy.modelling.models)
- [ ] NewData: New data added. 
  - _Q: Need to pass the data?_
- [ ] DataRemoved: Data has been removed. 
  - _Q: Need to pass the id of removed data?_
- [ ] ViewportChanged: A viewport has been change 
  - _Q: view id?, new limits?_

**Comment by ibusko** [comment]
How do we signal that a fit has finished and has new results to be reported? Maybe DataRefresh could be used for that, but in that case I suggest we change the "re-read all data" with something more descriptive. Something that says that not only data has to be re-read (I am assuming this refers to externally input data) but also new data of _any_ sort has become available, such as from a Fitter instance. Or maybe we use a separate signal for that?

**Comment by nmearl** [comment]
To be quite blunt, the scope of the component structures is pretty ill-defined at the moment. For instance, what does it mean to refresh data? Whose data are we refreshing? Who is doing the refreshing? What object would receive the "NewData" signal? Where do they store the new data?

I'm a bit concerned that we are still too fragmented on the project structure. For instance, are we approaching this from the command-line up, or from the GUI down?

**Comment by ibusko** [comment]
I have the impression that, although we started with the idea that both command-line and GUI use should be present, we are drifting towards a preference for the GUI m.o.. I mean, for this sprint, we are dropping the command-line mode. But we should keep in mind that in the future it should happen, and thus we should avoid blocking ourselves out of that route.

**Comment by nmearl** [comment]
Let me qualify my previous statement a bit.

### Command-line up

#### Package approach
- Packages are imported.
- Data objects created on-the-fly.
- Akin to using numpy/scipy objects and packages.
- No defined `Model` object.
- Not clear where signal functionality lies (where do they come from?).
- Creating a viewer in the namespace defeats the purpose of signals and slots because you already have direct access.
- What would a Controller even be in this context?

#### Centralized object approach
- User imports a `Model` object which contains all signals and functions (i.e. single entry point for the rest of the package features).
- User adds data to the `Model` instance; pre-defined signals are emitted, etc.
- User can create a viewer instance to which the model instance gets passed.
- Not clear what the use of a singal/slot system is if you already have direct access to viewer instance.
- Again, a Controller doesn't seem necessary (the user is essentially the controller, mediating the behavior between the Viewer and Model).

### GUI down

This proposes the tools in SpecView be developed like any packaged toolset that Astropy currently has. The GUI is a single means of associating the tools within a single context (MVC in this case).
- Model and Viewer are implicit in the construction of Qt applications.
  - This means that core SpecView package outside this GUI context acts like a numpy/scipy/astropy package.
  - If used with no GUI, does not require the user to explicitly create `Model` instances.
- Signals/slots are already managed and defined, but are within the GUI Model-Viewer association.
- Can include iPython/Console widget to manually manipulate Model within the Qt relational paradigm.
  - Model is already slotted to Viewer; no need to maintain relationship.
- Signal/Slot paradigm as developed by Qt is foremost for a Model/Viewer approach -- Controller not necessary.
- This inherently dissociates the MVC from the SpecView package. That is, MVC exists in the context of the GUI, while the package lives as toolkit functions.

**Comment by nmearl** [comment]
If we are going to go the GUI down route, I _strongly_ think we should forego a general signal/slot solution. Not doing so would mean we are maintaining two signal/slot methods: the general one, and the Qt one.

In the GUI model, all data items become AbstractDataItems with pre-defined signals and slots. An AbstractDataModel, which is also created, knows how to maintain and display AbstractDataItems. This also means that the entire GUI framework knows how to implicitly interact with the model. Essentially, a generic signal/slot or hub approach is really just making it more difficult from the GUI perspective.

Again, this foregoes a controller completely, as the Qt paradigm is really only Model/Viewer.

**Comment by stscieisenhamer** [comment]
For the purposes of the sprint, keeping everything central around the gui is probably the best. Any other options require a bit more design.  I'm good with that.

**Comment by stscieisenhamer** [comment]
sorry, didn't finish the thought, was interrupted.

As had been discussed, any of the other options can be expanded into if need be. the app, as is, will provide enough framework to design out, or decide if necessary, any other system.
