### ISSUE TITLE
Experiment with pyqtgraph exporting

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#5]

**Comment by stscieisenhamer** [comment]
I went through many of the relevant pyqtgraph canned examples, doing exports to matplotlib.

What it does is create a mpl widget, with the standard mpl toolbar, leaving the only real option of remember graphics state to the mpl save.

Also, must of the demos did not produce anything very usable in the mpl widget either.

**Comment by nmearl** [comment]
Our use-case is quite unique. In cases where data is easily portable (i.e. simply line plotting), the matplotlib export feature seems to work fine for me.

I'd move to simply create our own interface between the objects and a matplotlib customized widget. Since we understand the data formats, we can easily encapsulate the requisite functionality in a custom widget.

**Comment by stscieisenhamer** [comment]
Closing since this will be dealt with as part of issue #8.
