### ISSUE TITLE
matplotlib vs. others

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/specview#6]
Currently, the "other" is pyqtgraph as the primary graphcs/plot widget.

The main question seems to focus on a down-range desire to be able to make publication quality plots. This desire is currently influencing what technology is being used for the interactive tool.

**Comment by stscieisenhamer** [comment]
IMHO, this is a case of the "tail wagging the dog". As the sprint team had decided, using the "grid" of explore vs. publish, the focus of the tool will be exploratory and the technology should best match that.

In particular, the main output of an exploratory tool is more data/science related rather than plots and graphs themselves, beyond the crude generalities of what was being looked at.

There will be plenty of opportunity, and there are existing tools for, taking what was examined, from the data standpoint, and then reproduce/refine for publication.

Much of what should be remembered by the tool, and what the outputs of tool should be will be other issues such as #7 and #8.

**Comment by hcferguson** [comment]
Matplotlib is the "conservative" choice in that it is more mature. For one-d spectral analysis, I'm not sure how much we need the better interactive performance of PyQtGraph. That's why having some simple reference implementations of interactive plotting, overlays, and region selection, even if ugly code, might be useful during this sprint, if we can convince ourselves that it will might give a fair indication of relative performance.

Another consideration is whether making the GUI features and interactivity is easier to implement in PyQtGraph than in matplotlib. Doing the reference implementations might help to figure that out as well.
